/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0-M7
 * Generated at: 2025-04-24 07:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.UserModel;

public final class editUserProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.UserModel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

UserModel model = (UserModel) session.getAttribute("model");
if (model == null) {
	response.sendRedirect("userLogin.jsp");
	return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Edit User Profile</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\tbackground: #f4f6f9;\r\n");
      out.write("\tpadding: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("\tmax-width: 450px; /* reduced width */\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tbox-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, textarea, select {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus, textarea:focus, select:focus {\r\n");
      out.write("\tborder-color: #007BFF;\r\n");
      out.write("\tbox-shadow: 0 0 5px rgba(0, 123, 255, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions button {\r\n");
      out.write("\tpadding: 10px 20px;\r\n");
      out.write("\tbackground-color: #007BFF;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-actions button:hover {\r\n");
      out.write("\tbackground-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flex-row {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\tgap: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flex-item {\r\n");
      out.write("\tflex: 1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form-container\">\r\n");
      out.write("\t\t<h2>Edit Profile</h2>\r\n");
      out.write("\t\t<form action=\"updateUserProfile.jsp\" method=\"post\"\r\n");
      out.write("\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label for=\"firstName\">First Name:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"firstName\" name=\"firstName\" value=\"");
      out.print(model.getFirstName());
      out.write("\"\r\n");
      out.write("\t\t\t\trequired> <label for=\"lastName\">Last Name:</label> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" id=\"lastName\" name=\"lastName\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(model.getLastName());
      out.write("\" required> <label\r\n");
      out.write("\t\t\t\tfor=\"email\">Email:</label> <input type=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\tname=\"email\" value=\"");
      out.print(model.getEmail());
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Age & Gender side-by-side -->\r\n");
      out.write("\t\t\t<div class=\"flex-row\">\r\n");
      out.write("\t\t\t\t<div class=\"flex-item\">\r\n");
      out.write("\t\t\t\t\t<label for=\"age\">Age:</label> <input type=\"number\" id=\"age\"\r\n");
      out.write("\t\t\t\t\t\tname=\"age\" value=\"");
      out.print(model.getAge());
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"flex-item\">\r\n");
      out.write("\t\t\t\t\t<label for=\"gender\">Gender:</label> <select id=\"gender\"\r\n");
      out.write("\t\t\t\t\t\tname=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Male\"\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print("Male".equals(model.getGender()) ? "selected" : "");
      out.write(">Male</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Female\"\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print("Female".equals(model.getGender()) ? "selected" : "");
      out.write(">Female</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Other\"\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print("Other".equals(model.getGender()) ? "selected" : "");
      out.write(">Other</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label for=\"address\">Address:</label>\r\n");
      out.write("\t\t\t<textarea id=\"address\" name=\"address\" rows=\"3\" required>");
      out.print(model.getAddress());
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label for=\"phone\">Phone Number:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\tid=\"phone\" name=\"phone\" value=\"");
      out.print(model.getPhone());
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Add education and experience -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"action\" value=\"updateUserProfile\">Update Profile</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
