/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0-M7
 * Generated at: 2025-04-24 06:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Header with Right Menu and User Dropdown</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tbackground-color: #2c3e50;\r\n");
      out.write("\tpadding: 10px 20px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-section {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tgap: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\ttransition: color 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a:hover {\r\n");
      out.write("\tcolor: #f39c12;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-dropdown {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-button {\r\n");
      out.write("\tbackground-color: #2c3e50;\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\ttransition: background-color 0.6s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tmin-width: 180px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:last-child:hover {\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-dropdown:hover .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-dropdown {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button {\r\n");
      out.write("\tbackground-color: #2c3e50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 10px 30px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\ttransition: background-color 0.6s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button:hover {\r\n");
      out.write("\tcolor: #f39c12;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tmin-width: 260px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-dropdown-content a {\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-dropdown:hover .menu-dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"logo\">Talent Hub</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"right-section\">\r\n");
      out.write("\t\t\t<div class=\"nav-links\">\r\n");
      out.write("\t\t\t\t");

				String role = (String) session.getAttribute("role");
				if ("user".equalsIgnoreCase(role)) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"applications.jsp\">Applications</a> \r\n");
      out.write("\t\t\t\t");

				} else if ("company".equalsIgnoreCase(role)) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"post-job.jsp\">Post a Job</a>\r\n");
      out.write("\t\t\t\t<div class=\"menu-dropdown\">\r\n");
      out.write("\t\t\t\t\t<button class=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\tApplications\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu-dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"manage-applications.jsp\">Manage Applications</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"past-applications.jsp\">Past Applications</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

				} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"about.jsp\">About</a> <a href=\"contact.jsp\">Contact</a>\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"user-dropdown\">\r\n");
      out.write("\t\t\t\t");

				String first = (String) request.getAttribute("firstname");
				String last = (String) request.getAttribute("lastname");

				String displayName = "Guest";
				
				if (first != null && last != null) {
					displayName = first + " " + last;
				} else {
					// Fallback if you still want to check session or other logic
					String sessionName = (String) session.getAttribute("username");
					if (sessionName != null) {
						displayName = sessionName;
					}
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"user-button\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(displayName);
      out.write("\r\n");
      out.write("\t\t\t\t\t▼\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"userProfile.jsp\">View Profile</a> \r\n");
      out.write("\t\t\t\t\t");
 
					if(role.equalsIgnoreCase("user"))
					{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"userLogin.jsp\">Logout</a>\r\n");
      out.write("\t\t\t\t\t");
 
					}
					else if(role.equalsIgnoreCase("company"))
					{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"companyLogin.jsp\">Logout</a>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
