/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0-M7
 * Generated at: 2025-04-23 04:12:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class jobSeekerRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Job Seeker Registration</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Import Poppins font -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Internal CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\tbackground-color: #f4f4f4;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registration-container {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tmargin: 40px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tbox-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmax-width: 350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2:hover {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-container {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tpadding: 12px 0px;\r\n");
      out.write("\tpadding-left: 8px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #fff; /* Keep the input background white */\r\n");
      out.write("\tz-index: 1; /* Ensure the input stays behind the label */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus {\r\n");
      out.write("\tborder-color: #4d90fe;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Floating label */\r\n");
      out.write("input:focus+label, input:not(:placeholder-shown)+label {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #4d90fe;\r\n");
      out.write("\ttop: -9px; /* Adjusted to align with the upper edge of the text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 10px; /* Slightly adjusted to align with the text */\r\n");
      out.write("\tleft: 8px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\ttransition: all 0.2s ease;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("\tz-index: 2; /* Ensure the label stays above the input */\r\n");
      out.write("\tbackground-color: #fff; /* To avoid background showing through */\r\n");
      out.write("\tpadding: 0 4px;\r\n");
      out.write("\t/* Add some padding to avoid label overlapping input edges */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit-btn {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 12px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit-btn:hover {\r\n");
      out.write("\tbackground-color: #45a049;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tborder: 2px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin-top: -10px; text-align : center;\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"registration-container\">\r\n");
      out.write("\t\t<h2>Job Seeker Registration</h2>\r\n");
      out.write("\t\t<form action=\"UserController\" method=\"post\" id=\"registrationForm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Full Name Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"firstName\" name=\"firstName\" placeholder=\" \"\r\n");
      out.write("\t\t\t\t\trequired> <label for=\"firstName\">First Name</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Last Name Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"lastName\" name=\"lastName\" placeholder=\" \"\r\n");
      out.write("\t\t\t\t\trequired> <label for=\"lastName\">Last Name</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Email Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"email\" id=\"email\" name=\"email\" placeholder=\" \" required>\r\n");
      out.write("\t\t\t\t<label for=\"email\">Email Address</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Age & Gender Fields -->\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tstyle=\"display: flex; justify-content: space-between; gap: 10px; margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t<!-- Age Dropdown -->\r\n");
      out.write("\t\t\t\t<div style=\"flex: 1;\">\r\n");
      out.write("\t\t\t\t\t<select name=\"age\" id=\"age\" required\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%; padding: 8px; border-radius: 4px; border: 1px solid #ccc; font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" disabled selected hidden>Age</option>\r\n");
      out.write("\t\t\t\t\t\t");

						for (int i = 18; i <= 50; i++) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Gender Dropdown -->\r\n");
      out.write("\t\t\t\t<div style=\"flex: 1;\">\r\n");
      out.write("\t\t\t\t\t<select name=\"gender\" id=\"gender\" required\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%; padding: 8px; border-radius: 4px; border: 1px solid #ccc; font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" disabled selected hidden>Gender</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Male\">Male</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Female\">Female</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Other\">Other</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Address Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"address\" name=\"address\" placeholder=\" \">\r\n");
      out.write("\t\t\t\t<label for=\"address\">Address</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Phone Number Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\" \" required>\r\n");
      out.write("\t\t\t\t<label for=\"phone\">Phone Number</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Password Field -->\r\n");
      out.write("\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" placeholder=\" \"\r\n");
      out.write("\t\t\t\t\trequired> <label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"errorMessages\" class=\"error\">\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ error }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"submit-btn\" name=\"value\" value=\"register\">Register</button>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer Start -->\r\n");
      out.write("\t");

    	request.setAttribute("footerStyle", "position: fixed; bottom: 0; width: 100%; padding: 10px 0; background-color: #f0f2f5; color: #000000; text-align: center; font-size: 12px; font-family: 'Poppins', sans-serif;");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- Footer End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
