/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0-M7
 * Generated at: 2025-04-24 12:39:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.UserModel;
import com.model.EducationModel;
import com.model.ProjectModel;
import java.util.List;
import java.util.Map;

public final class userProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.ProjectModel");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.model.EducationModel");
    _jspx_imports_classes.add("com.model.UserModel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

UserModel model = (UserModel) session.getAttribute("model");
EducationModel emodel = (EducationModel) session.getAttribute("emodel");
Map<String, Object> userProjects = (Map<String, Object>) session.getAttribute("userProjects");

if (model == null || emodel == null || userProjects == null) {
	response.sendRedirect("userLogin.jsp");
	return;
}

List<ProjectModel> projects = (List<ProjectModel>) userProjects.get("projects");
List<String> languagesList = (List<String>) userProjects.get("languages");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>User Profile</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Poppins', sans-serif;\r\n");
      out.write("\tbackground: linear-gradient(to right, #fdfdfd, #e6f0ff);\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tpadding: 60px 60px 40px 60px;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tmax-width: 1100px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header h1 {\r\n");
      out.write("\tfont-size: 42px;\r\n");
      out.write("\tcolor: #1e3a5f;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section {\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 30px 35px;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\tbox-shadow: 0 8px 20px rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section h2 {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tcolor: #007BFF;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tpadding-bottom: 8px;\r\n");
      out.write("\tborder-bottom: 2px solid #007BFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p strong {\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".project-entry {\r\n");
      out.write("\tbackground-color: #f4faff;\r\n");
      out.write("\tpadding: 15px 20px;\r\n");
      out.write("\tborder-left: 4px solid #007BFF;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styling */\r\n");
      out.write(".button-group {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: flex-end;\r\n");
      out.write("\tgap: 20px;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-group button {\r\n");
      out.write("\tpadding: 12px 25px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\ttransition: background 0.3s ease, transform 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn {\r\n");
      out.write("\tbackground-color: #007BFF;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn:hover {\r\n");
      out.write("\tbackground-color: #0056b3;\r\n");
      out.write("\ttransform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn {\r\n");
      out.write("\tbackground-color: #dc3545;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn:hover {\r\n");
      out.write("\tbackground-color: #a71d2a;\r\n");
      out.write("\ttransform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<h1>User Profile</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Profile Info -->\r\n");
      out.write("\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t<h2>Personal Information</h2>\r\n");
      out.write("\t\t\t<p><strong>Full Name:</strong> ");
      out.print(model.getFirstName());
      out.write(' ');
      out.print(model.getLastName());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Email:</strong> ");
      out.print(model.getEmail());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Age:</strong> ");
      out.print(model.getAge());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Gender:</strong> ");
      out.print(model.getGender());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Address:</strong> ");
      out.print(model.getAddress());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Phone Number:</strong> ");
      out.print(model.getPhone());
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Education -->\r\n");
      out.write("\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t<h2>Education</h2>\r\n");
      out.write("\t\t\t<p><strong>Institute:</strong> ");
      out.print(emodel.getInstituteName());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Degree:</strong> ");
      out.print(emodel.getDegreeName());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Description:</strong> ");
      out.print(emodel.getDegreeDescription());
      out.write("</p>\r\n");
      out.write("\t\t\t<p><strong>Passout Year:</strong> ");
      out.print(emodel.getPassoutYear());
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Projects -->\r\n");
      out.write("\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t<h2>Projects</h2>\r\n");
      out.write("\t\t\t");
 for (int i = 0; i < projects.size(); i++) {
				ProjectModel p = projects.get(i);
				String langs = languagesList.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"project-entry\">\r\n");
      out.write("\t\t\t\t\t<p><strong>Project Name:</strong> ");
      out.print(p.getName());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<p><strong>Description:</strong> ");
      out.print(p.getDescription());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t<p><strong>Languages Used:</strong> ");
      out.print(langs);
      out.write("</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Buttons -->\r\n");
      out.write("\t\t<div class=\"button-group\">\r\n");
      out.write("\t\t\t<button class=\"edit-btn\" onclick=\"window.location.href='editUserProfile.jsp'\">Edit Profile</button>\r\n");
      out.write("\t\t\t<form id=\"deleteForm\" action=\"UserController\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"deleteUserProfile\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"delete-btn\" onclick=\"confirmDelete()\">Delete Profile</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction confirmDelete() {\r\n");
      out.write("\t\t\tif (confirm(\"Are you sure you want to delete your profile?\")) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"deleteForm\").submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
