/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0-M7
 * Generated at: 2025-04-22 07:42:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>Talent Hub</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Import Poppins font -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      background-color: #000;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-container {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 40px;\r\n");
      out.write("      margin-bottom: 80px; /* space for footer */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      color: black;\r\n");
      out.write("      padding: 30px 50px;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      box-shadow: 0 4px 12px rgba(255, 255, 255, 0.1);\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      transition: transform 0.9s ease, box-shadow 0.4s ease;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: flex-start;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      width: 220px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:hover {\r\n");
      out.write("      height: 150px;\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("      box-shadow: 0 6px 18px rgba(255, 255, 255, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-title {\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      transition: margin-bottom 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-buttons {\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      transform: translateY(20px);\r\n");
      out.write("      transition: opacity 0.3s ease, transform 0.3s ease;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:hover .card-buttons {\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("      transform: translateY(0);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card button {\r\n");
      out.write("      width: 140px;\r\n");
      out.write("      padding: 10px 0;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("      background-color: #000;\r\n");
      out.write("      color: white;\r\n");
      out.write("      transition: background-color 0.3s ease;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card button:hover {\r\n");
      out.write("      background-color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 8px 0;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 10px;\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"card-container\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <div class=\"card-title\">JOB SEEKER</div>\r\n");
      out.write("      <div class=\"card-buttons\">\r\n");
      out.write("        <a href=\"jobSeekerRegistration.jsp\">\r\n");
      out.write("    \t\t<button type=\"button\">Registration</button>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"jobSeekerRegistration.jsp\">\r\n");
      out.write("    \t\t<button type=\"button\">Login</button>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <div class=\"card-title\">COMPANY</div>\r\n");
      out.write("      <div class=\"card-buttons\">\r\n");
      out.write("      <a href=\"jobSeekerRegistration.jsp\">\r\n");
      out.write("        <button>Registration</button>\r\n");
      out.write("      </a>  \r\n");
      out.write("      <a href=\"jobSeekerRegistration.jsp\">\r\n");
      out.write("        <button>Login</button>\r\n");
      out.write("      </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    Talent Hub rights are reserved and developed by Parth Sabhani ©2025\r\n");
      out.write("  </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
